// <auto-generated />
using Ejemplo_Blazor_EF.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ejemplo_Blazor_EF.Data.Migrations
{
    [DbContext(typeof(ReunionContext))]
    [Migration("20260320194243_MigracionInicial")]
    partial class MigracionInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Ejemplo_Blazor_EF.Models.Reunion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Desc")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("Virtual")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.ToTable("reunion", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Desc = "Revisión de arquitectura: Implementación de patrón MVVM en el módulo de reuniones.",
                            Virtual = true
                        },
                        new
                        {
                            Id = 2,
                            Desc = "Sincronización de equipo: Discusión sobre la migración de SQL Server a PostgreSQL.",
                            Virtual = false
                        },
                        new
                        {
                            Id = 3,
                            Desc = "Capacitación técnica: Mejores prácticas para el uso de Dependency Injection en .NET 8.",
                            Virtual = false
                        },
                        new
                        {
                            Id = 4,
                            Desc = "Daily meeting: Seguimiento de tareas del Proyecto Verano y despliegue en Railway.",
                            Virtual = true
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
